### ISSUE TITLE
AxisTickColor

### ISSUE THREAD

**Issue by kokoa4** [gellerda/FancyCandles#20]
Hi, This chart is very useful to me. 
can you split AxisTickColor to AxisBorder and AxisText? It might be awesome.

**Comment by gellerda** [comment]
Hello.
Done! I have added the [ChartAreaBorderColor](https://gellerda.github.io/FancyCandles/api/FancyCandles.CandleChart.html#FancyCandles_CandleChart_ChartAreaBorderColor) property. I have left the AxisTickColor property as it was.

**Comment by kokoa4** [comment]
![untitled](https://user-images.githubusercontent.com/79257457/126763597-69fa43e5-e6d8-4299-b8e6-f64dfeb30c48.png)

Thank you for your update! 
I ask you one more thing to customize border more specifically.
I need more specific color control : separate AxisTickColor with Timeline border.
(I want to change axis text color only.)

I think It would be great. Thanks.

**Comment by gellerda** [comment]
I have made some changes (in the repository, not in the Nuget package). Check it out. It looks much better now.
I suppose you want to get rid of the horizontal lines in the time scale. I don't think it is a good design decision. The middle horizontal line is necessary because it separates two horizontal levels of time labels. Making this lines in different color than the tick labels will entail making the ticks (not the tick labels) in the same color, otherwise it would look ridiculous. Note that all vertical lines in the time scale area is time ticks. The only suggestion I can understand is to get rid of the lowest horizontal line, but it is rather controversial IMHO. 
You can edit the `OnRender` method of the `TimeTicksElement` class to adjust the appearance of the horizontal lines in the time scale area. The last three lines of code in this method draw this three lines:
`drawingContext.DrawLine(axisTickPen, new Point(0, topTimePanelY), new Point(RenderSize.Width, topTimePanelY));
drawingContext.DrawLine(axisTickPen, new Point(0, centerTimePanelY), new Point(RenderSize.Width, centerTimePanelY));
drawingContext.DrawLine(axisTickPen, new Point(0, RenderSize.Height), new Point(RenderSize.Width, RenderSize.Height));`

**Comment by kokoa4** [comment]
Oh, yes I wanted to control two lines placed under time text.
instead of using Nuget I downloaded library and edited as you mentiond, finally set up like what I wanted.
I love it. Thank you
